#!/bin/bash

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
   $GEOSERVER_HOME/bin/startup.sh
   echo $! > /var/run/geoserver.pid
   ;;
stop)
   cat /var/run/geoserver.pid | kill
   rm /var/run/geoserver.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/geoserver.pid ]; then
      PID =
      echo geoserver is running, pid=''
   else
      echo geoserver is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
